const translations={
  en:{nav_services:'Services',nav_process:'Process',nav_contact:'Contact',eyebrow:'Custom software studio',hero_title:'We build modern apps that move your business forward.',hero_lead:'Mobile apps, web platforms, cloud systems and digital tools designed with performance, security and growth in mind.',cta_email:'Start a project',cta_services:'Explore services',services_eyebrow:'What we do',services_title:'Technology solutions for digital products.',s1_title:'Software Development',s1_text:'Custom systems, business tools, admin panels, APIs and integrations built around your workflow.',s2_title:'Mobile Apps',s2_text:'Native-feeling apps for iOS and Android, from MVPs to scalable production platforms.',s3_title:'Web Platforms',s3_text:'Modern responsive websites, portals, dashboards and SaaS experiences ready for growth.',s4_title:'Cloud & Automation',s4_text:'Cloud infrastructure, data workflows, automation and secure deployment for digital operations.',process_eyebrow:'How we work',process_title:'From idea to launch with clarity.',process_text:'We transform ideas into reliable digital products through strategy, design, development, testing and continuous improvement.',step1:'Discovery and scope',step2:'UX/UI and architecture',step3:'Development and integrations',step4:'Launch and support',showcase_eyebrow:'Built for impact',showcase_title:'Clean interfaces. Strong backend. Scalable systems.',showcase_text:'Ixotec helps businesses create digital platforms that look professional, work fast and are ready to evolve.',contact_eyebrow:'Contact',contact_title:'Tell us about your next project.',contact_text:'Send us your idea, requirements or current challenge. We will help you define the best technology path.',form_name:'Name',form_message:'Message',form_send:'Send message',footer:'Development of apps tailored to your business.'},
  es:{nav_services:'Servicios',nav_process:'Proceso',nav_contact:'Contacto',eyebrow:'Estudio de software a medida',hero_title:'Creamos apps modernas que impulsan tu negocio.',hero_lead:'Aplicaciones móviles, plataformas web, sistemas en la nube y herramientas digitales diseñadas para rendimiento, seguridad y crecimiento.',cta_email:'Iniciar proyecto',cta_services:'Ver servicios',services_eyebrow:'Qué hacemos',services_title:'Soluciones tecnológicas para productos digitales.',s1_title:'Desarrollo de Software',s1_text:'Sistemas a medida, herramientas empresariales, paneles administrativos, APIs e integraciones adaptadas a tu flujo de trabajo.',s2_title:'Apps Móviles',s2_text:'Aplicaciones para iOS y Android, desde MVPs hasta plataformas escalables listas para producción.',s3_title:'Plataformas Web',s3_text:'Sitios modernos, portales, dashboards y experiencias SaaS responsivas listas para crecer.',s4_title:'Nube y Automatización',s4_text:'Infraestructura cloud, flujos de datos, automatización y despliegue seguro para operaciones digitales.',process_eyebrow:'Cómo trabajamos',process_title:'De la idea al lanzamiento con claridad.',process_text:'Transformamos ideas en productos digitales confiables mediante estrategia, diseño, desarrollo, pruebas y mejora continua.',step1:'Descubrimiento y alcance',step2:'UX/UI y arquitectura',step3:'Desarrollo e integraciones',step4:'Lanzamiento y soporte',showcase_eyebrow:'Hecho para generar impacto',showcase_title:'Interfaces limpias. Backend sólido. Sistemas escalables.',showcase_text:'Ixotec ayuda a las empresas a crear plataformas digitales profesionales, rápidas y listas para evolucionar.',contact_eyebrow:'Contacto',contact_title:'Cuéntanos sobre tu próximo proyecto.',contact_text:'Envíanos tu idea, requerimientos o reto actual. Te ayudamos a definir el mejor camino tecnológico.',form_name:'Nombre',form_message:'Mensaje',form_send:'Enviar mensaje',footer:'Desarrollo de apps a la medida de tu negocio.'}
};
let current='en';
function setLang(lang){current=lang;document.documentElement.lang=lang;document.querySelectorAll('[data-i18n]').forEach(el=>{el.textContent=translations[lang][el.dataset.i18n]});document.querySelectorAll('[data-placeholder-'+lang+']').forEach(el=>{el.placeholder=el.dataset['placeholder'+(lang==='en'?'En':'Es')]});document.getElementById('langBtn').textContent=lang==='en'?'ES':'EN'}
document.getElementById('langBtn').addEventListener('click',()=>setLang(current==='en'?'es':'en'));
document.getElementById('year').textContent=new Date().getFullYear();
const io=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('show')})},{threshold:.12});
document.querySelectorAll('.reveal').forEach(el=>io.observe(el));
setLang('en');
